# Generated by Django 3.0 on 2021-05-12 08:04

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('aboutid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('metatitle', models.CharField(blank=True, max_length=100, null=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='about/')),
                ('detail', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('createdate', models.DateTimeField(auto_now_add=True, null=True)),
                ('editeddate', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'About',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contactid', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
                ('note', models.TextField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'Contact',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedbackid', models.AutoField(primary_key=True, serialize=False)),
                ('namefeedback', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, max_length=100, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
                ('createdate', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'Feedback',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('footerid', models.AutoField(primary_key=True, serialize=False)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('status', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Footer',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('slideid', models.AutoField(primary_key=True, serialize=False)),
                ('slidename', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='slide/')),
                ('displayorder', models.IntegerField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('descriptions', models.TextField(blank=True, null=True)),
                ('createdate', models.DateTimeField(auto_now_add=True, null=True)),
                ('editeddate', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Slide',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tagid', models.AutoField(primary_key=True, serialize=False)),
                ('tagname', models.TextField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'Tag',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('productcategoryid', models.AutoField(primary_key=True, serialize=False)),
                ('productcategoryname', models.CharField(max_length=100)),
                ('metatitle', models.CharField(blank=True, max_length=250, null=True)),
                ('displayoder', models.IntegerField(blank=True, null=True)),
                ('SEOtitle', models.TextField(blank=True, max_length=100, null=True)),
                ('createdate', models.DateTimeField(auto_now_add=True, null=True)),
                ('editeddate', models.DateTimeField(auto_now=True, null=True)),
                ('metaKeywords', models.TextField(blank=True, max_length=250, null=True)),
                ('metaDescriptions', models.TextField(blank=True, max_length=250, null=True)),
                ('isenable', models.BooleanField(blank=True, null=True)),
                ('parentcategoryid', models.ForeignKey(blank=True, db_column='ParentCategoryId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='homepage.ProductCategory')),
            ],
            options={
                'db_table': 'ProductCategory',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productid', models.AutoField(primary_key=True, serialize=False)),
                ('productcode', models.CharField(blank=True, max_length=50, null=True)),
                ('productname', models.TextField(blank=True, null=True)),
                ('size', models.CharField(blank=True, max_length=100, null=True)),
                ('metatitle', models.TextField(blank=True, null=True)),
                ('descriptions', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('productimage', models.ImageField(upload_to='product/')),
                ('moreimage', models.ImageField(blank=True, null=True, upload_to='productdetail/')),
                ('url', models.URLField(blank=True, null=True)),
                ('price', models.CharField(blank=True, max_length=50, null=True)),
                ('promotionprice', models.CharField(blank=True, max_length=50, null=True)),
                ('includeVAT', models.CharField(blank=True, max_length=150, null=True)),
                ('viewcounts', models.IntegerField(blank=True, null=True)),
                ('createdate', models.DateTimeField(auto_now_add=True, null=True)),
                ('editeddate', models.DateTimeField(auto_now=True, null=True)),
                ('productcategoryid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.ProductCategory')),
            ],
            options={
                'db_table': 'Product',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=0)),
                ('quantity', models.IntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderid', models.AutoField(primary_key=True, serialize=False)),
                ('startdate', models.DateTimeField(auto_now_add=True)),
                ('ordereddate', models.DateTimeField(blank=True, null=True)),
                ('ordered', models.BooleanField(default=False)),
                ('shippingaddress', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('ORDER', 'ĐẶT HÀNG'), ('CONFIRM', 'XÁC NHẬN'), ('DELIVERING', 'ĐANG VẬN CHUYỂN'), ('COMPLETED', 'HOÀN TẤT')], max_length=50)),
                ('completeddate', models.DateTimeField(blank=True, null=True)),
                ('items', models.ManyToManyField(to='homepage.OrderItem')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('blogtagid', models.AutoField(primary_key=True, serialize=False)),
                ('blogtagname', models.CharField(blank=True, max_length=100, null=True)),
                ('tagid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Tag')),
            ],
            options={
                'db_table': 'BlogTag',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('blogcategoryid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('metatitle', models.CharField(blank=True, max_length=250, null=True)),
                ('displayorder', models.IntegerField(blank=True, null=True)),
                ('SEOtitle', models.CharField(blank=True, max_length=250, null=True)),
                ('createdate', models.DateTimeField(auto_now_add=True, null=True)),
                ('editeddate', models.DateTimeField(auto_now=True, null=True)),
                ('metaKeywords', models.CharField(blank=True, max_length=50, null=True)),
                ('note', models.CharField(blank=True, max_length=250, null=True)),
                ('parentid', models.ForeignKey(blank=True, db_column='ParentId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='homepage.BlogCategory')),
            ],
            options={
                'db_table': 'BlogCategory',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('blogid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, max_length=100, null=True)),
                ('metatitle', models.TextField(blank=True, max_length=250, null=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('blogimage', models.ImageField(upload_to='news/')),
                ('details', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('createdate', models.DateTimeField(auto_now_add=True, null=True)),
                ('editeddate', models.DateTimeField(auto_now=True, null=True)),
                ('metaKeywords', models.CharField(blank=True, max_length=250, null=True)),
                ('metaDescriptions', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.BooleanField(blank=True, null=True)),
                ('isenable', models.BooleanField(blank=True, null=True)),
                ('viewcount', models.IntegerField(blank=True, null=True)),
                ('tagid', models.CharField(blank=True, max_length=50, null=True)),
                ('blogcategoryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.BlogCategory')),
            ],
            options={
                'db_table': 'Blog',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=250, null=True)),
                ('password', models.CharField(max_length=32)),
                ('address', models.TextField(blank=True, max_length=500, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='account/')),
                ('note', models.TextField(blank=True, null=True)),
                ('createdate', models.DateField(auto_now_add=True, null=True)),
                ('editdate', models.DateTimeField(auto_now=True, null=True)),
                ('isenable', models.BooleanField(blank=True, default=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Account',
                'managed': True,
            },
        ),
    ]
