# Generated by Django 3.0 on 2021-05-20 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20210518_2340'),
        ('homepage', '0002_auto_20210517_1353'),
    ]

    operations = [
    ]
