# Generated by Django 3.0 on 2021-05-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_merge_20210520_1214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slide',
            old_name='displayorder',
            new_name='display',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='fullname',
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
    ]
