# Generated by Django 3.0 on 2021-05-28 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_contact_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('WAIT', 'CHỜ XỬ LÝ'), ('SPAM', 'SPAM'), ('COMPLETED', 'HOÀN TẤT')], default='Wait', max_length=50),
        ),
    ]
