# Generated by Django 3.0 on 2021-06-19 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_blog_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('WAIT', 'CHỜ XỬ LÝ'), ('SPAM', 'SPAM'), ('COMPLETED', 'HOÀN TẤT')], default='WAIT', max_length=50),
        ),
    ]
