# Generated by Django 3.0 on 2021-06-19 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_auto_20210619_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcategory',
            name='parentid',
        ),
    ]
