# Generated by Django 3.0 on 2021-06-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_remove_blogcategory_parentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='parent_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
