# Generated by Django 3.0 on 2021-06-19 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_blogcategory_parent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='parent_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
